### ISSUE TITLE
KeyError: 'test'

### ISSUE THREAD

**Issue by tbrown122387** [ucbds-infra/otter-grader#215] opened 2021-02-04 18:04 UTC
**Describe the bug**
Autograder fails to grade student submissions.

Here's the error message:

```
Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 11, in <module>
    run_autograder('/autograder')
  File "/root/miniconda3/envs/otter-gradescope-env/lib/python3.7/site-packages/otter/run/run_autograder/__init__.py", line 48, in main
    output = run_autograder(options)
  File "/root/miniconda3/envs/otter-gradescope-env/lib/python3.7/site-packages/otter/run/run_autograder/run_autograder.py", line 182, in run_autograder
    script=script,
  File "/root/miniconda3/envs/otter-gradescope-env/lib/python3.7/site-packages/otter/execute/__init__.py", line 132, in grade_notebook
    extra_tests.append(OKTestFile.from_file(t))
  File "/root/miniconda3/envs/otter-gradescope-env/lib/python3.7/site-packages/otter/test_files/ok_test.py", line 134, in from_file
    test_spec = test_globals['test']
KeyError: 'test'
```

Here's how I generated the `autograder.zip` file to upload to Gradescope

```
(base) taylor@taylor-Precision-T1700:~/UVa/all_teaching/spring21_1602/labs/lab01$ ls
error.jpg  lab01.ipynb  map.jpg  METADATA  numberline_0.png  numberline_1.png  tests
(base) taylor@taylor-Precision-T1700:~/UVa/all_teaching/spring21_1602/labs/lab01$ otter generate -t tests/
(base) taylor@taylor-Precision-T1700:~/UVa/all_teaching/spring21_1602/labs/lab01$ ls
autograder.zip  lab01.ipynb  METADATA          numberline_1.png
error.jpg       map.jpg      numberline_0.png  tests
```

**Comment by chrispyles** [comment] 2021-02-04 18:14
Can you share your test file/s? This error seems to be caused by a malformed test file.

**Comment by tbrown122387** [comment] 2021-02-04 18:23
Thanks for the quick response. 

I am upgrading `otter` with `pip install otter-grader --upgrade` and re-uploading `autograder.zip`. Let me check if that fixes it before I share my test file. I was running `2.0.6` and now I'm running `2.1.2`

**Comment by tbrown122387** [comment] 2021-02-04 18:32
Here's one of the files:

```
test = {
  'name': 'q3_1_2',
  'points': 1,
  'suites': [
    {
      'cases': [
        {
          'code': r"""
          >>> # It looks like you didn't give anything the name;
          >>> # seconds_in_a_decade.  Maybe there's a typo, or maybe you;
          >>> # just need to run the cell below Question 3.2 where you defined;
          >>> # seconds_in_a_decade.  (Click that cell and then click the "run;
          >>> # cell" button in the menu bar above.);
          >>> 'seconds_in_a_decade' in vars()
          True
          """,
          'hidden': False,
          'locked': False
        },
        {
          'code': r"""
          >>> # It looks like you didn't change the cell to define;
          >>> # seconds_in_a_decade appropriately.  It should be a number,;
          >>> # computed using Python's arithmetic.  For example, this is;
          >>> # almost right:;
          >>> #   seconds_in_a_decade = 10*365*24*60*60;
          >>> seconds_in_a_decade != ...
          True
          """,
          'hidden': False,
          'locked': False
        },
        {
          'code': r"""
          >>> # It looks like you didn't account for leap years.;
          >>> # There were 2 leap years and 8 non-leap years in this period.;
          >>> # Leap years have 366 days instead of 365.;
          >>> seconds_in_a_decade != 315360000
          True
          """,
          'hidden': False,
          'locked': False
        },
        {
          'code': r"""
          >>> seconds_in_a_decade == 315532800
          True
          """,
          'hidden': False,
          'locked': False
        }
      ],
      'scored': True,
      'setup': '',
      'teardown': '',
      'type': 'doctest'
    }
  ]
}
```

**Comment by chrispyles** [comment] 2021-02-04 18:35
Are there any .py files in your tests directory that don’t define a global variable called `test`?

**Comment by tbrown122387** [comment] 2021-02-04 18:36
Just `__init__.py`, which is empty

**Comment by tbrown122387** [comment] 2021-02-04 18:58
same error...
```
The results uploaded to Gradescope were not formatted correctly. Please see
http://gradescope-autograders.readthedocs.io/en/latest/specs/#output-format
for more details.

Use the "Debug via SSH" button below to debug this issue.


We did not receive any results for this submission.

The autograder produced the following output:

  _________        __          __               
 /  _____  \    __|  |__    __|  |__               
|  /     \  |  |__    __|  |__    __|   _______    _  _____
| |       | |     |  |        |  |     |  ___  |  | |/ ____|
| |       | |     |  |        |  |     | |___| |  |   /    
| |       | |     |  |        |  |     | ______|  |  |
|  \_____/  |     |  |_       |  |_    | |_____   |  |
 \_________/       \ __|       \ __|    \______|  |__|
                                                v2.1.2
 

Hello, World!
👋, 🌏!
First this line is printed,
the the whole, 🌏
and then this one.
A whole new cell, ♪🌏♪
This line is missing something.
This line is missing something.
2
3
The larger distance from the average height among these two people is 0.478 meters.
Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 11, in <module>
    run_autograder('/autograder')
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/__init__.py", line 48, in main
    output = run_autograder(options)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/run_autograder.py", line 192, in run_autograder
    script=script,
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/execute/__init__.py", line 132, in grade_notebook
    extra_tests.append(OKTestFile.from_file(t))
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/test_files/ok_test.py", line 134, in from_file
    test_spec = test_globals['test']
KeyError: 'test'
```

**Comment by tbrown122387** [comment] 2021-02-04 20:03
I removed `__init__.py` from the zip's `tests/` directory and all is well now

**Comment by chrispyles** [comment] 2021-02-04 20:09
Closing this issue

**Closed by chrispyles** 2021-02-04 20:09 UTC
Labels: bug
