### ISSUE TITLE
Error encountered while generating and submitting PDF

### ISSUE THREAD

**Issue by ericchouzyb** [ucbds-infra/otter-grader#597] opened 2023-01-05 22:12 UTC
**Describe the bug**

Error encountered while generating and submitting PDF:
There was an error generating your LaTeX; showing full error message:
    Failed to run "['xelatex', 'notebook.tex', '-quiet']" command:
    This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2022/dev/Debian) (preloaded format=xelatex)
     restricted \write18 enabled.

If the error above is related to xeCJK or fandol in LaTeX and you don't require this functionality, try running again with no_xecjk set to True or the --no-xecjk flag.

**To Reproduce**
1. Prepare the assignment notebook
2. Run otter assign 
3. upload the zip file under autograder to Gradescope
4. test autograder by submitting a solution notebook

**Expected behavior**
A pdf should be generated and submitted to another Gradescope assignment.

**Versions**
Python: 3.7.4
Otter:  4.2.1
nbconvert: 6.4.4

**Additional context**
Besides the failure mentioned above, I am also wondering how I can set no_xecjk to True. I can do that locally but it is not in one of the configurations in the Assignment Metadata. 

Also I have tried these two commands:

```
otter export -v   --no-xecjk .\Homework1_F22_Solution.ipynb dist

otter export -v  --exporter html  .\Homework1_F22_Solution.ipynb dist
```

it gives `Failed to run "xelatex notebook.tex -quiet" command:` and 
 `otter.export.utils.WkhtmltopdfNotFoundError: PDF via HTML indicated but wkhtmltopdf not found` , respectively.

**Comment by cindygr** [comment] 2023-01-29 17:13
I have a very similar problem; I build the autograder zip/student version of the .ipynb file using otter assign. When the student tries to run the last line of their file

# Save your notebook first, then run this cell to export your submission.
grader.export(run_tests=True)

The error is generated by bibtex. I have tried setting the --no-xecjk flag but it doesn't help

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/13035767/215342102-95004be8-7f62-437f-9cd4-2829b3965274.png">

It fails to create a pdf and so fails to create a zip file. The autograder, run on the same file in gradescope, also fails to produce a pdf, with the same error. 

I have resorted to downloading the files and writing a script to convert them to pdfs using jupyter-nbconvert.

**Comment by chrispyles** [comment] 2023-01-29 20:33
This error usually occurs when the LaTeX file generated from the notebook has no contents (because Otter filtered out all non-manually graded cells). Does your assignment have any questions marked `manual: true` in their question configs?

**Comment by cindygr** [comment] 2023-01-30 23:01
Yes, there was one question marked for manual grading.

**Comment by chrispyles** [comment] 2023-01-31 03:07
> So Otter will filter out all non-manually graded cells automatically? Because I have set filtering as False in the Assignment Metadata.

Yes, Otter does PDF filter automatically unless `grader.export` has `filtering=False` set (which Otter Assign sets if you have `export_cell: filtering: false` in your assignment config).

@ericchouzyb @cindygr can you both share an otter assign notebook that reproduces this bug? It sounds like in both cases the LaTeX shouldn't be empty. Feel free to PM them to me in Otter's Slack (link in README) if you don't want to share these notebooks publicly.

**Comment by chrispyles** [comment] 2023-06-25 19:32
This hasn't been updated in a while so I'm going to close it but feel free to reopen if you're still running into this issue.

**Closed by chrispyles** 2023-06-25 19:32 UTC
Labels: bug
