### ISSUE TITLE
Otter grading fails when checking more than 2 matplotlib objects

### ISSUE THREAD

**Issue by JudoWill** [ucbds-infra/otter-grader#269] opened 2021-07-19 15:36 UTC
**Describe the bug**

I'm trying to create exercise for students to try different visualizations with matplotlib. I'm checking their work by saving the output to an axis object and then interrogating those properties.

In general:
```python
ax_a = sns.barplot(data = table.to_df(), x = 'col2', y = 'col1', hue='col3') # SOLUTION
```
and then in the tests
```python
# Test #
xticks = {tick.get_text() for tick in ax_a.get_xticklabels()}
expected = {'True', 'False'}
assert (xticks == expected), 'Wrong patient ticks, did you plot right independent variable?'
```
This all works great. 

Then, for some reason, when any more than 2 plots are in the notebook. The otter autochecker fails, yet generates notebooks that pass when run in interactive jupyter notebooks.

**To Reproduce**

I've attached a `minimal_example.ipynb` file
[minimal_example.ipynb.txt](https://github.com/ucbds-infra/otter-grader/files/6842190/minimal_example.ipynb.txt)
. Currently, when running `otter assign` it fails yet it creates a autograder solution that passes in the distribution folder.

If you delete the third question. `otter assign` runs correctly. It doesn't even matter if its part of the doc tests. Just generating the third plot causes the previous two to fail. This is even more perplexing because I intentionally saved each plot into its own axis so I could robustly validate them even if the student ran things out of order.

**Expected behavior**
3 or more plots.

**Versions**

Interactive notebooks otter-grader 1.1.6 and general Colab environment.

Generating/grading version 2.1.7, Python 3.7.10

**Additional context**

Is there an alternative strategy for validating the "correct plot" was made aside from `manual` mode?

**Comment by chrispyles** [comment] 2021-08-07 04:57
try adding a call to `plt.close` at the end of your last test for each plot. There are some issues caused by `plt.gca` and other matplotlib functions due to the fact that we're executing what was a notebook as a script.

**Comment by chrispyles** [comment] 2021-08-17 03:35
Closing this since there's been no reply but please feel free to reopen if there is still an issue.

**Comment by JudoWill** [comment] 2021-08-17 12:44
I'm still here. I still have this issue with classes that are starting imminently. I've only been able to work-around the issue by limiting myself to 2 or less figures if I ever want to validate them.

Whatever bug is here is too deep in the internals for me to understand how to root out.

Were you able to reproduce the bug given my example code? Perhaps that would help me debug it if its only on my system.

Can you reopen the issue and respond?

**Comment by JudoWill** [comment] 2021-08-17 15:12
@chrispyles, seems like your response got lost in my master inbox. But, I tried adding a `plt.close()` both within the cell of the last Test, after the last test, and within the original solution cell. None work. Is there an arrangement that worked for you in my minimal example above?

**Comment by chrispyles** [comment] 2021-08-17 15:53
@JudoWill Two things:

* I mistyped: add `plt.close("all")` at the end of the last test of each question. 
* You need to set `init_cell: true` in your assignment metadata. Part of the reason this fails is because the notebook doesn't instantiate `otter.Notebook`, which means that tests can't get executed at the specific points in each notebook where they're supposed to; instead, they get executed at the end. For the `plt.close("all")` solution, we need the checks to get executed after each question, otherwise they'll just fail after the first call to `plt.close("all")`.

I tested this out on your provided example and it worked for me; let me know if it doesn't for you. I'm attaching the notebook file. Let me know if this fixes things on your end.

[minimal_example.ipynb.txt](https://github.com/ucbds-infra/otter-grader/files/7001364/minimal_example.ipynb.txt)

**Comment by JudoWill** [comment] 2021-08-19 15:37
Hmmmmmm, the plot thickens.

I can get yours to work but I can't use an `init_cell` in my distribution. Since I'm working on Colab and I'm required by school policy to host all of my material in a specific system that only allows downloads of files (not directories of files, no nbcheckout or wgets from a Github allowed) I have to do a bit of a dance to get zip-files unzipped, account for restarts (where the zip-file is already unzipped), account for having to put two separate assignments worth of otter-tests into the same zip-file using alternate directory paths, while still gracefully accepting that otter-grade always uses `tests/` as its directory when making docker containers for otter-grade, and installing the pinned version of Otter that works on Colab.

All of that has to happen above the `init_cell`. Which doesn't seem possible. I went down a bit of a rabbit hole seeing if I could make the init-cell custom, but it seems to be written by a Python function deep in the code and doesn't accept any way of defining it from a template notebook. I didn't want to make a fork just to change my init-cell. And because the name of the files/paths change, it would need to be a parameterized function.

Here's the custom `init_cell` that I'm using, it is the first executable cell in all of my notebooks:
```python
# Setting up the Colab environment. DO NOT EDIT!
import os.path

test_zip = "Week06-files.zip"
if not (os.path.exists(test_zip) or os.path.exists('lab-tests') or os.path.exists('tests')):
    raise EnvironmentError('NO OTTER FILES FOUND. Did you forget to upload them?')
elif os.path.exists('lab-tests'):
    pass
elif os.path.exists(test_zip):
    ! unzip Week06-files.zip

# I had to add this because I found sometimes warnings made on Colab 
# don't match the grader's warnings, making grading weird.
import warnings
warnings.filterwarnings("ignore")    

    
try:
    import otter
except ImportError:
    ! pip install -q otter-grader==1.1.6
    import otter

grader = otter.Notebook('lab-tests')

```

from the same Week06-files.zip I also unpack a 'walkthrough-tests' directory for a another assignment (which will properly instantiate the grader with the right directory), any data or library files that might be needed, etc. I use a `cookiecutter` to create all of the boilerplate code and `snakemake` to manage packing the test-files into zip directories, rename notebooks, and generally re-organize for a smoother experience in my teaching system (BbLearn).

Is there something else that needs to get initialized for the grader to work right? Do I need some trick to skip the cell when doing the grading? I tried using your `plt.close('all')` trick on my assignments but it still doesn't work. It seems pretty clear that its still confusing which plot goes with which question when its doing the doc-tests.

**Comment by chrispyles** [comment] 2021-08-19 17:49
OK so if I understand your initial post correctly, the machine you're running otter assign on has Otter v2.1.7, right?

If this is the case, try using this as your init cell instead and set `init_cell: false`.

```python
# Setting up the Colab environment. DO NOT EDIT!
import os.path

try:
    import otter

except ImportError:
    ! pip install -q otter-grader==1.1.6
    import otter

if otter.__version__ == "1.1.6":
    test_zip = "Week06-files.zip"
    if not (os.path.exists(test_zip) or os.path.exists('lab-tests') or os.path.exists('tests')):
        raise EnvironmentError('NO OTTER FILES FOUND. Did you forget to upload them?')
    elif os.path.exists('lab-tests'):
        pass
    elif os.path.exists(test_zip):
        ! unzip Week06-files.zip

    # I had to add this because I found sometimes warnings made on Colab 
    # don't match the grader's warnings, making grading weird.
    import warnings
    warnings.filterwarnings("ignore")    

    grader = otter.Notebook('lab-tests')

else:
    grader = otter.Notebook("minimal_example.ipynb")
```

This will instantiate Otter and go through your normal Colab setup if v1.1.6 is installed but on your machine will just instantiate a `Notebook` so that tests can be run.

**Comment by chrispyles** [comment] 2021-08-19 19:02
BTW re: the issue of Otter v1.1.6 being the only compatible version, I've just opened #310 to bring the `otter.Notebook` class back into compatibility with Colab beginning with Otter v3.0.0.b3.

**Comment by JudoWill** [comment] 2021-08-19 19:11
Eureka! Now I see the difference. When I do the `otter grade` command, it never properly instantiates the grader because the `lab-tests` folder never gets created (because I can't make the zip file with the tests until _after_ `otter assign` completes) and so I can't include it as one of the `files` items in the `meta` section.

Now for a quick hot-fix of 9 assignments before they get released. I imagine this would be nearly impossible to fix once students have already used and submitted the notebooks.

Thanks for the help. I would've never guessed this one.

**Comment by chrispyles** [comment] 2021-08-19 20:30
Great! I'll close this issue then but please open another if you run into any other issues.

**Closed** 2021-08-19 20:30 UTC
Labels: bug
