### ISSUE TITLE
Autograder fails on Gradescope for R .ipynb files

### ISSUE THREAD

**Issue by ttimbers** [ucbds-infra/otter-grader#725] opened 2023-09-03 22:17 UTC
I upgraded to the newest version of otter-grader this year and the R notebooks that I have used for the past two years with otter-grader no longer work. They work fine with `otter assign`, and the container will build on Gradescope, however when I test the autograder on Gradescope I get:

```
The results uploaded to Gradescope were not formatted correctly. Please see
http://gradescope-autograders.readthedocs.io/en/latest/specs/#output-format
for more details.

Use the "Debug via SSH" button below to debug this issue.


We did not receive any results for this submission.

The autograder produced the following output:

Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 3, in <module>
    from otter.run.run_autograder import main as run_autograder
ModuleNotFoundError: No module named 'otter'
```

I can also see that the R notebook example [here](https://github.com/ucbds-infra/ottr-sample) hasn't been updated in 2 years - do you have a working example of R notebooks with the new version of otter-grader? This issue I have is specific to ipynb because if I convert the file to an Rmd and use otter-grader there it works fine.

**Comment by chrispyles** [comment] 2023-09-05 06:06
Usually when errors like this occur it's because there was an error that was thrown while trying to build the conda environment when Gradescope builds the grading image. Were there any errors in the build output?

**Comment by joelostblom** [comment] 2023-09-28 19:14
I faced the same issue and when looking into it more, it seems like the env files did not use to require inclusion of the `otter-grader` package, but since v5 the do, could that be correct? Using the env file from the docs or the more minimal ones in #739 works for me for R and Py assignments.

**Comment by chrispyles** [comment] 2024-02-20 06:04
> it seems like the env files did not use to require inclusion of the otter-grader package, but since v5 the do, could that be correct?

otter-grader has always been included in the image builds by otter (unless you're using overwrite_requirements, in which case otter doesn't edit your requirements to make sure it's in there). before v5, it was listed in a requirements.txt file, but in v5, all dependencies were merged into a single conda environment.yml file.

The ottr sample noteooks in ucbds-infra/ottr-sample should still work; I don't think there have been any breaking changes to R notebook handling since they were last updated, but I will double check.

**Comment by chrispyles** [comment] 2024-02-20 07:01
I've checked the sample notebook and it does seem correct; otter assign worked when I ran it and I was able to upload the zip to Gradescope and it ran successfully on the solutions notebook. I'm going to close this now since this isn't can't be reproduced but please feel free to reopen it if it persists.

**Closed by chrispyles** 2024-02-20 07:01 UTC
Labels: bug
