### ISSUE TITLE
Hidden tests not hidden

### ISSUE THREAD

**Issue by drjbarker** [ucbds-infra/otter-grader#181] opened 2021-01-13 09:30 UTC
I'm writing jupyter notebooks to be used by students who may run them in environments without otter installed and therefore cannot have any otter function calls in the notebook. For grading purposes all of my tests are "hidden tests". From the documentation I understood that these would not produce any inline check cells like `grader.check("q1")`, but at the moment these ARE created for every hidden test.

Is this a bug or intended behaviour?

I can manually edit the notebook in a text editor and remove these cells and the grading all works fine. But from my reading of the docs and the source code this seems to be a bug. If it is then please let me know and I'll try to track it down and fix it.

**Comment by chrispyles** [comment] 2021-01-13 17:44
Can you share a screenshot/snippet from your master notebook that reproduces this bug?

**Comment by drjbarker** [comment] 2021-01-13 17:49
For example this:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/53377004/104489537-a4ff9c00-55c7-11eb-94e1-2518bbb4849e.png">

produces this:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/53377004/104489581-b5b01200-55c7-11eb-92b6-9d0ec8f9754c.png">

But I was expecting with hidden tests only that there would be no grader check.

**Comment by chrispyles** [comment] 2021-01-13 17:52
What version of otter are you running? You can get this with `otter --version`

**Comment by drjbarker** [comment] 2021-01-13 17:54
Python version: 3.8.5
Otter-Grader version: 1.1.6
Running on MacOS (Big Sur)

Installed in a conda environment via pip.

**Comment by chrispyles** [comment] 2021-01-13 18:04
OK upon further investigation this is not a bug but a design choice. Basically, Otter Assign won't include a `grader.check` cell if 1) the tests are all hidden AND 2) there is no cell for students to respond. This is to account for variable name collisions, to ensure that if a question has all hidden tests but a variable being tests gets reassigned later, the hidden tests still get run at the correct point during execution.

A workaround for your use case would be to move the `BEGIN QUESTION` block to a Markdown cell between the solution and test cells:

````
[new Markdown cell]
# A1
**(a)** Case `x` to type `complex`

**[1 mark]**


[new code cell]
x = -9.0
x = complex(x) # SOLUTION


[new Markdown cell]
```
BEGIN QUESTION
name: A1a
```


[new code cell]
## HIDDEN TEST ##
print(type(x))
````

Hope this helps!

**Comment by drjbarker** [comment] 2021-01-14 09:16
Thanks, that works. I had assumed that a solution could only come after a question but not I understand that it's simply for the removal of code for the assignment and is not directly linked to the question.

**Comment by chrispyles** [comment] 2021-01-14 16:45
Great!

**Closed by chrispyles** 2021-01-14 16:45 UTC
Labels: bug
