### ISSUE TITLE
Docker login required for tutorial?

### ISSUE THREAD

**Issue by dfeehan** [ucbds-infra/otter-grader#213] opened 2021-02-03 18:00 UTC
Thanks again for your help with the tutorial yesterday.

I'm trying again today, and now I'm encountering what looks like a problem in the Docker setup when I run `otter grade`. I'm not completely sure, but it seems possible that I don't have authorization to pull a Docker image? I'm pasting the output I get at the end of this message - please let me know if more information would be helpful. And sorry if I am missing something here.

Thanks again for all of your work on this project.

Command and error message:

```
❯ otter grade -p submissions/ipynbs -a dist/autograder/autograder.zip -j meta.json --pdfs -v
Found JSON metadata...
Launching docker containers...
[+] Building 3.5s (6/15)
 => [internal] load build definition from Dockerfile                                                                        0.0s
 => => transferring dockerfile: 37B                                                                                         0.0s
 => [internal] load .dockerignore                                                                                           0.0s
 => => transferring context: 2B                                                                                             0.0s
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest                                                   0.0s
 => [internal] load build context                                                                                           0.0s
 => => transferring context: 258B                                                                                           0.0s
 => CACHED [ 1/11] FROM docker.io/ucbdsinfra/otter-grader                                                                   0.0s
 => ERROR [ 2/11] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lis  3.4s
------
 > [ 2/11] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*:
#5 0.492 Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
#5 0.657 Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
#5 0.713 Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
#5 0.713   At least one invalid signature was encountered.
#5 0.784 Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
#5 0.784   At least one invalid signature was encountered.
#5 0.802 Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#5 1.291 Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
#5 1.291   At least one invalid signature was encountered.
#5 1.377 Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
#5 1.529 Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
#5 1.529   At least one invalid signature was encountered.
#5 1.534 Fetched 324 kB in 1s (248 kB/s)
#5 1.534 Reading package lists...
#5 2.301 W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
#5 2.301 W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
#5 2.301 W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
#5 2.301 W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
#5 2.301 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  At least one invalid signature was encountered.
#5 2.301 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  At least one invalid signature was encountered.
#5 2.301 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  At least one invalid signature was encountered.
#5 2.301 W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  At least one invalid signature was encountered.
#5 2.301 W: Some index files failed to download. They have been ignored, or old ones used instead.
#5 2.346 Reading package lists...
#5 3.068 Building dependency tree...
#5 3.204 Reading state information...
#5 3.348 unzip is already the newest version (6.0-25ubuntu1).
#5 3.348 unzip set to manually installed.
#5 3.348 The following NEW packages will be installed:
#5 3.349   curl dos2unix libcurl4
#5 3.360 0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
#5 3.360 Need to get 769 kB of archives.
#5 3.360 After this operation, 2458 kB of additional disk space will be used.
#5 3.361 E: You don't have enough free space in /var/cache/apt/archives/.
------
executor failed running [/bin/sh -c apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*]: exit code: 100
Traceback (most recent call last):
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/models/containers.py", line 810, in run
    detach=detach, **kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/models/containers.py", line 868, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: otter-grade:6df55d65e3f80bf5d5e486fc63994a83")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=6df55d65e3f80bf5d5e486fc63994a83&fromImage=otter-grade

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dennis/opt/anaconda3/bin/otter", line 8, in <module>
    sys.exit(run_otter())
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/runner.py", line 56, in run_otter
    args.func(**kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/__init__.py", line 104, in main
    pdfs=pdfs
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 111, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 111, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 144, in grade_assignments
    container = client.containers.run(image, detach=True, tty=True)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/models/containers.py", line 812, in run
    self.client.images.pull(image, platform=platform)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/models/images.py", line 445, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for otter-grade, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
```

**Comment by chrispyles** [comment] 2021-02-04 17:13
So the error at the bottom is pretty misleading; the actual issue is near the top in the Docker image build output. For some reason, the Docker image failed to build, which is why Otter errored out later when looking for the Docker image it created. I'm not sure the cause of the error that caused the Docker build to fail, seems to be something to do with verifying the apt packages it's attempting to install.

**Comment by dfeehan** [comment] 2021-02-04 18:01
OK, thanks! That was helpful. (Also, I edited my previous post to improve the formatting of the output - sorry it was so messy before.)

Anyway, I'm not exactly sure what was wrong, but I updated Docker and then deleted a bunch of images related to my previous attempt at the tutorial. Then I re-ran the grade command.  Now things progressed much further -- but I still get an error. Now, when I run the `otter grade` command in the tutorial, I see:

```
❯ otter grade -p submissions/ipynbs -a dist/autograder/autograder.zip -j meta.json --pdfs -v
Found JSON metadata...
Launching docker containers...
[+] Building 182.3s (16/16) FINISHED
 => [internal] load build definition from Dockerfile                                                                        0.0s
 => => transferring dockerfile: 37B                                                                                         0.0s
 => [internal] load .dockerignore                                                                                           0.0s
 => => transferring context: 2B                                                                                             0.0s
 => [internal] load metadata for docker.io/ucbdsinfra/otter-grader:latest                                                   2.0s
 => CACHED [ 1/11] FROM docker.io/ucbdsinfra/otter-grader@sha256:05a20f9ff7f36ceb021dd21ed1353e203a49795ce24a3fb8b90c7b87b  0.0s
 => => resolve docker.io/ucbdsinfra/otter-grader@sha256:05a20f9ff7f36ceb021dd21ed1353e203a49795ce24a3fb8b90c7b87b2d17971    0.0s
 => [internal] load build context                                                                                           0.0s
 => => transferring context: 258B                                                                                           0.0s
 => [ 2/11] RUN apt-get update && apt-get install -y curl unzip dos2unix && apt-get clean && rm -rf /var/lib/apt/lists/* /  6.6s
 => [ 3/11] RUN mkdir -p /autograder/source                                                                                 0.3s
 => [ 4/11] ADD dist/autograder/autograder.zip /tmp/autograder.zip                                                          0.0s
 => [ 5/11] RUN unzip -d /autograder/source /tmp/autograder.zip                                                             0.3s
 => [ 6/11] RUN cp /autograder/source/run_autograder /autograder/run_autograder                                             0.3s
 => [ 7/11] RUN dos2unix /autograder/run_autograder /autograder/source/setup.sh                                             0.3s
 => [ 8/11] RUN chmod +x /autograder/run_autograder                                                                         0.3s
 => [ 9/11] RUN apt-get update && bash /autograder/source/setup.sh && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/  148.1s
 => [10/11] RUN mkdir -p /autograder/submission                                                                             0.5s
 => [11/11] RUN mkdir -p /autograder/results                                                                                0.3s
 => exporting to image                                                                                                     23.2s
 => => exporting layers                                                                                                    23.1s
 => => writing image sha256:a2c8a9a3a7e7dd339977ec34f1f5ddf2b3837219c9b62fafda422588f3c031e8                                0.0s
 => => naming to docker.io/library/otter-grade:6df55d65e3f80bf5d5e486fc63994a83                                             0.0s
Launched container eaa05a3cc2c6...
Launched container 3b2b64898993...
Launched container 1bacddba4673...
Launched container 22dbad05cd79...
Grading notebooks in container eaa05a3cc2c6...
Grading notebooks in container 3b2b64898993...
Grading notebooks in container 1bacddba4673...
Grading notebooks in container 22dbad05cd79...
Stopping container eaa05a3cc2c6...
Stopping container 1bacddba4673...
Stopping container 22dbad05cd79...
Stopping container 3b2b64898993...
Launched container 7bc6f884307d...
Launched container 9196cd48f760...
Grading notebooks in container 7bc6f884307d...
Grading notebooks in container 9196cd48f760...
Stopping container 7bc6f884307d...
Stopping container 9196cd48f760...
Traceback (most recent call last):
  File "/Users/dennis/opt/anaconda3/bin/otter", line 8, in <module>
    sys.exit(run_otter())
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/runner.py", line 56, in run_otter
    args.func(**kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/__init__.py", line 104, in main
    pdfs=pdfs
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 111, in launch_grade
    return [df.result() for df in finished_futures[0]]
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 111, in <listcomp>
    return [df.result() for df in finished_futures[0]]
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/dennis/opt/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/dennis/opt/anaconda3/lib/python3.7/site-packages/otter/grade/containers.py", line 168, in grade_assignments
    assert exit_code == 0, f"Container {container_id} failed with output:\n{output.decode('utf-8')}"
AssertionError: Container 1bacddba4673 failed with output:
  _________        __          __
 /  _____  \    __|  |__    __|  |__
|  /     \  |  |__    __|  |__    __|   _______    _  _____
| |       | |     |  |        |  |     |  ___  |  | |/ ____|
| |       | |     |  |        |  |     | |___| |  |   /
| |       | |     |  |        |  |     | ______|  |  |
|  \_____/  |     |  |_       |  |_    | |_____   |  |
 \_________/       \ __|       \ __|    \______|  |__|
                                                v2.1.2


Traceback (most recent call last):
  File "/autograder/source/run_otter.py", line 11, in <module>
    run_autograder('/autograder')
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/__init__.py", line 48, in main
    output = run_autograder(options)
  File "/root/miniconda3/envs/otter-env/lib/python3.7/site-packages/otter/run/run_autograder/run_autograder.py", line 118, in run_autograder
    with zipfile.ZipFile(zips[0])  as zf:
IndexError: list index out of range
```

**Comment by chrispyles** [comment] 2021-02-11 18:57
Yeah, sorry about this. This was an oversight while updating the tutorial for v2. I've pushed an update to the documentation so you should be able to see it in the next few hours.

**Comment by chrispyles** [comment] 2021-02-14 07:07
Closing this thread but please reopen it if the issue is not resolved.

**Closed by chrispyles** 2021-02-14 07:07 UTC
