### ISSUE TITLE
Running the otter-grader tutorial

### ISSUE THREAD

**Issue by jake-bobowski** [ucbds-infra/otter-grader#783] opened 2024-02-28 02:25 UTC
I'm trying to work with the otter-grader tutorial as described <a href = "https://otter-grader.readthedocs.io/en/latest/tutorial.html">here</a>.

When I run the ```otter assign``` command:
```python
otter assign '.\demo.ipynb' dist
```
the ```dist``` directory is created and it has the correct ```autograder``` and ```student``` subdirectories, each populated with the correct files.  However, I get the following warnings from ```otter assign```:
```
C:\Users\jbobowsk\venv\otter_20240227\lib\site-packages\zmq\_future.py:679: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  self._get_loop()
C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py:1896: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  handle._run()
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 55590)
Traceback (most recent call last):
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\jbobowsk\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\jbobowsk\venv\otter_20240227\lib\site-packages\otter\execute\logging.py", line 43, in handle
    chunk = self.connection.recv(4)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
----------------------------------------
```

Grading the mock submissions included with the tutorial works.  I'm using the following command:
```python
otter grade -n test -a '.\dist\autograder\demo-autograder_2024_02_27T14_09_02_247551.zip' -v --ext zip .\submissions\zips
```

I'm wondering why I'm getting the warnings/errors when running ```otter assign``` and how to fix things so they stop.  I'm running 
Python 3.10.6, Otter-grader 5.1.4 and the following packages in my virtual environment:
```
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
anyio                         3.6.1
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.8
astunparse                    1.6.3
attrs                         22.1.0
Babel                         2.10.3
backcall                      0.2.0
beautifulsoup4                4.11.1
bleach                        5.0.1
cachetools                    5.2.0
certifi                       2022.9.24
cffi                          1.15.1
charset-normalizer            2.1.1
click                         8.1.3
colorama                      0.4.5
contourpy                     1.0.5
cycler                        0.11.0
debugpy                       1.6.3
decorator                     5.1.1
defusedxml                    0.7.1
dill                          0.3.5.1
docutils                      0.19
entrypoints                   0.4
executing                     1.1.0
fastjsonschema                2.16.2
fica                          0.2.0
fonttools                     4.37.4
future                        0.18.2
google-api-core               2.10.1
google-api-python-client      2.64.0
google-auth                   2.12.0
google-auth-httplib2          0.1.0
google-auth-oauthlib          0.5.3
googleapis-common-protos      1.56.4
gspread                       5.5.0
httpimport                    0.7.2
httplib2                      0.20.4
idna                          3.4
imagesize                     1.4.1
ipykernel                     6.16.0
ipylab                        1.0.0
ipysheet                      0.5.0
ipython                       8.5.0
ipython-genutils              0.2.0
ipywidgets                    7.7.2
jedi                          0.18.1
Jinja2                        3.1.2
jsonschema                    4.16.0
jupyter_client                7.3.5
jupyter-core                  4.11.1
jupyter-server                1.19.1
jupyterlab-pygments           0.2.2
jupyterlab-widgets            1.1.1
jupytext                      1.14.1
kiwisolver                    1.4.4
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
matplotlib                    3.6.0
matplotlib-inline             0.1.6
mdit-py-plugins               0.3.1
mdurl                         0.1.2
mistune                       2.0.4
mpmath                        1.2.1
nbclient                      0.7.0
nbconvert                     7.1.0
nbformat                      5.6.1
nest-asyncio                  1.5.6
notebook                      6.4.12
numpy                         1.23.3
oauthlib                      3.2.1
otter-grader                  5.1.4
packaging                     21.3
pandas                        1.5.0
pandocfilters                 1.5.0
parso                         0.8.3
pdfkit                        1.0.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           24.0
prometheus-client             0.14.1
prompt-toolkit                3.0.31
protobuf                      4.21.7
psutil                        5.9.2
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.21
pydantic                      1.10.2
Pygments                      2.13.0
pyparsing                     3.0.9
PyPDF2                        2.11.0
pyrsistent                    0.18.1
python-dateutil               2.8.2
python-on-whales              0.52.0
pytz                          2022.4
pywin32                       303
pywinpty                      2.0.8
PyYAML                        6.0
pyzmq                         24.0.1
requests                      2.28.1
requests-oauthlib             1.3.1
rsa                           4.9
scipy                         1.9.1
Send2Trash                    1.8.0
setuptools                    63.2.0
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        5.2.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.5.1
sympy                         1.11.1
terminado                     0.16.0
tinycss2                      1.1.1
toml                          0.10.2
tornado                       6.4
tqdm                          4.64.1
traitlets                     5.4.0
typer                         0.6.1
typing_extensions             4.3.0
uncertainties                 3.1.7
uritemplate                   4.1.1
urllib3                       1.26.12
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.4.1
wheel                         0.42.0
widgetsnbextension            3.6.1
wrapt                         1.14.1
```

Any suggestions would be greatly appreciated!  Thanks @jake-bobowski

**Comment by jake-bobowski** [comment] 2024-02-28 03:31
I updated all packages in the virtual environment.  Now the only warning I get when when running ```otter assign``` is:
```
C:\Users\jbobowsk\venv\otter_20240227\lib\site-packages\zmq\_future.py:693: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  self._get_loop()
```
The packages installed in the virtual environment are now:
```
Package                       Version
----------------------------- ---------------
alabaster                     0.7.16
annotated-types               0.6.0
anyio                         4.3.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
astunparse                    1.6.3
async-lru                     2.0.4
attrs                         23.2.0
Babel                         2.14.0
backcall                      0.2.0
beautifulsoup4                4.12.3
bleach                        6.1.0
cachetools                    5.3.3
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
colorama                      0.4.6
comm                          0.2.1
contourpy                     1.2.0
cycler                        0.12.1
debugpy                       1.8.1
decorator                     5.1.1
defusedxml                    0.7.1
dill                          0.3.8
docutils                      0.20.1
entrypoints                   0.4
exceptiongroup                1.2.0
executing                     2.0.1
fastjsonschema                2.19.1
fica                          0.3.1
fonttools                     4.49.0
fqdn                          1.5.1
future                        1.0.0
google-api-core               2.17.1
google-api-python-client      2.119.0
google-auth                   2.28.1
google-auth-httplib2          0.2.0
google-auth-oauthlib          1.2.0
googleapis-common-protos      1.62.0
gspread                       6.0.2
h11                           0.14.0
httpcore                      1.0.4
httpimport                    1.3.1
httplib2                      0.22.0
httpx                         0.27.0
idna                          3.6
imagesize                     1.4.1
ipykernel                     6.29.3
ipylab                        1.0.0
ipysheet                      0.7.0
ipython                       8.22.1
ipython-genutils              0.2.0
ipywidgets                    8.1.2
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.3
json5                         0.9.17
jsonpointer                   2.4
jsonschema                    4.21.1
jsonschema-specifications     2023.12.1
jupyter_client                8.6.0
jupyter_core                  5.7.1
jupyter-events                0.9.0
jupyter-lsp                   2.2.3
jupyter_server                2.12.5
jupyter_server_terminals      0.5.2
jupyterlab                    4.1.2
jupyterlab_pygments           0.3.0
jupyterlab_server             2.25.3
jupyterlab_widgets            3.0.10
jupytext                      1.16.1
kiwisolver                    1.4.5
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.8.3
matplotlib-inline             0.1.6
mdit-py-plugins               0.4.0
mdurl                         0.1.2
mistune                       3.0.2
mpmath                        1.3.0
nbclient                      0.9.0
nbconvert                     7.16.1
nbformat                      5.9.2
nest-asyncio                  1.6.0
notebook                      7.1.1
notebook_shim                 0.2.4
numpy                         1.26.4
oauthlib                      3.2.2
otter-grader                  5.4.1
overrides                     7.7.0
packaging                     23.2
pandas                        2.2.1
pandocfilters                 1.5.1
parso                         0.8.3
pdfkit                        1.0.0
pickleshare                   0.7.5
pillow                        10.2.0
pip                           24.0
platformdirs                  4.2.0
prometheus_client             0.20.0
prompt-toolkit                3.0.43
protobuf                      4.25.3
psutil                        5.9.8
pure-eval                     0.2.2
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pycparser                     2.21
pydantic                      2.6.3
pydantic_core                 2.16.3
Pygments                      2.17.2
pyparsing                     3.1.1
PyPDF2                        3.0.1
pyrsistent                    0.20.0
python-dateutil               2.8.2
python-json-logger            2.0.7
python-on-whales              0.69.0
pytz                          2024.1
pywin32                       306
pywinpty                      2.0.13
PyYAML                        6.0.1
pyzmq                         25.1.2
referencing                   0.33.0
requests                      2.31.0
requests-oauthlib             1.3.1
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rpds-py                       0.18.0
rsa                           4.9
scipy                         1.12.0
Send2Trash                    1.8.2
setuptools                    63.2.0
six                           1.16.0
sniffio                       1.3.1
snowballstemmer               2.2.0
soupsieve                     2.5
Sphinx                        7.2.6
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
stack-data                    0.6.3
StrEnum                       0.4.15
sympy                         1.12
terminado                     0.18.0
tinycss2                      1.2.1
toml                          0.10.2
tomli                         2.0.1
tornado                       6.4
tqdm                          4.66.2
traitlets                     5.14.1
typer                         0.9.0
types-python-dateutil         2.8.19.20240106
typing_extensions             4.10.0
tzdata                        2024.1
uncertainties                 3.1.7
uri-template                  1.3.0
uritemplate                   4.1.1
urllib3                       2.2.1
wcwidth                       0.2.13
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.7.0
wheel                         0.42.0
widgetsnbextension            4.0.10
wrapt                         1.16.0
```

**Comment by chrispyles** [comment] 2024-02-29 03:08
I'm not sure what was causing the `An existing connection was forcibly closed by the remote host` error but it sounds like it was fixed by your package upgrades. The RuntimeWarning you're still getting isn't related to otter itself (it must be some incompatibility between packages in your environment; I've seen this warning before but never dug into its root cause) but it shouldn't hinder otter. Is otter assign now outputting the correct files?

**Comment by jake-bobowski** [comment] 2024-02-29 03:28
Thanks @chrispyles!  Yes, ```otter assign``` is generating the correct files.  I can assign demo.ipynb provided in the tutorial.  I can then successfully grade the mock submissions. We're currently using otter-graded 4.x in our courses.  I'm tentatively planning to switch over to otter-grader 5.x next September.

**Comment by chrispyles** [comment] 2024-02-29 03:56
OK, in that case I'm going to close this. Feel free to reopen or open a new issue if you run into any more issues.

**Closed by chrispyles** 2024-02-29 03:56 UTC
Labels: question
