### ISSUE TITLE
autograder.zip file hangs on build in Gradescope

### ISSUE THREAD

**Issue by taylorgibson** [ucbds-infra/otter-grader#143] opened 2020-10-21 18:24 UTC
**Describe the bug**
When uploading the `autograder.zip` file created from calling otter assign will occasionally hang while building in Gradescope.

**To Reproduce**
1. Create autograder files using `otter assign <filename>.ipynb`
2. Upload `autograder.zip` to a Gradescope assignment.

**Expected behavior**
The build should complete.

**Versions**
Python 3.8.5 and Otter Grader 1.1.2

**Additional context**
The final Build Output from the Configure Autograder section is as follows:

```
The build should result in a
Setting up xfonts-75dpi (1:1.0.4+nmu1) ...
Setting up xfonts-base (1:1.0.4+nmu1) ...
Setting up wkhtmltox (1:0.12.6-1.bionic) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.4ubuntu1).
build-essential set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcurl4-gnutls-dev : Conflicts: libcurl4-openssl-dev but 7.58.0-2ubuntu3.10 is to be installed
 libcurl4-openssl-dev : Conflicts: libcurl4-gnutls-dev but 7.58.0-2ubuntu3.10 is to be installed
[91mE: Unable to correct problems, you have held broken packages.
[0m[91m2020-10-21 13:36:54 URL:https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh [88867207/88867207] -> "/autograder/source/miniconda_install.sh" [1]
[0mPREFIX=/root/miniconda3
Unpacking payload ...
[91m
  0%|          | 0/35 [00:00<?, ?it/s][0m[91m
Extracting : ncurses-6.2-he6710b0_1.conda:   0%|          | 0/35 [00:00<?, ?it/s][0m[91m
Extracting : ncurses-6.2-he6710b0_1.conda:   3%|▎         | 1/35 [00:00<00:10,  3.25it/s][0m[91m
Extracting : tk-8.6.8-hbc83047_0.conda:   3%|▎         | 1/35 [00:00<00:10,  3.25it/s]   [0m[91m
Extracting : pyopenssl-19.1.0-py37_0.conda:   6%|▌         | 2/35 [00:00<00:10,  3.25it/s][0m[91m
Extracting : ca-certificates-2020.1.1-0.conda:   9%|▊         | 3/35 [00:00<00:09,  3.25it/s][0m[91m
Extracting : certifi-2020.4.5.1-py37_0.conda:  11%|█▏        | 4/35 [00:00<00:09,  3.25it/s] [0m[91m
Extracting : six-1.14.0-py37_0.conda:  14%|█▍        | 5/35 [00:00<00:09,  3.25it/s]        [0m[91m
Extracting : sqlite-3.31.1-h62c20be_1.conda:  17%|█▋        | 6/35 [00:00<00:08,  3.25it/s][0m[91m
Extracting : ruamel_yaml-0.15.87-py37h7b6447c_0.conda:  20%|██        | 7/35 [00:00<00:08,  3.25it/s][0m[91m
Extracting : pycosat-0.6.3-py37h7b6447c_0.conda:  23%|██▎       | 8/35 [00:00<00:08,  3.25it/s]      [0m[91m
Extracting : setuptools-46.4.0-py37_0.conda:  26%|██▌       | 9/35 [00:00<00:07,  3.25it/s]    [0m[91m
Extracting : pip-20.0.2-py37_3.conda:  29%|██▊       | 10/35 [00:00<00:07,  3.25it/s]      [0m[91m
Extracting : tqdm-4.46.0-py_0.conda:  31%|███▏      | 11/35 [00:00<00:07,  3.25it/s] [0m[91m
Extracting : pycparser-2.20-py_0.conda:  34%|███▍      | 12/35 [00:00<00:07,  3.25it/s][0m[91m
Extracting : chardet-3.0.4-py37_1003.conda:  37%|███▋      | 13/35 [00:00<00:06,  3.25it/s][0m[91m
Extracting : idna-2.9-py_1.conda:  40%|████      | 14/35 [00:00<00:06,  3.25it/s]          [0m[91m
Extracting : yaml-0.1.7-had09818_2.conda:  43%|████▎     | 15/35 [00:00<00:06,  3.25it/s][0m[91m
Extracting : libedit-3.1.20181209-hc058e9b_0.conda:  46%|████▌     | 16/35 [00:00<00:05,  3.25it/s][0m[91m
Extracting : cryptography-2.9.2-py37h1ba5d50_0.conda:  49%|████▊     | 17/35 [00:00<00:05,  3.25it/s][0m[91m
Extracting : openssl-1.1.1g-h7b6447c_0.conda:  51%|█████▏    | 18/35 [00:00<00:05,  3.25it/s]        [0m[91m
Extracting : requests-2.23.0-py37_0.conda:  54%|█████▍    | 19/35 [00:00<00:04,  3.25it/s]   [0m[91m
Extracting : wheel-0.34.2-py37_0.conda:  57%|█████▋    | 20/35 [00:00<00:04,  3.25it/s]   [0m[91m
Extracting : python-3.7.7-hcff3b4d_5.conda:  60%|██████    | 21/35 [00:00<00:04,  3.25it/s]
Extracting : python-3.7.7-hcff3b4d_5.conda:  63%|██████▎   | 22/35 [00:00<00:02,  4.48it/s]
Extracting : _libgcc_mutex-0.1-main.conda:  63%|██████▎   | 22/35 [00:00<00:02,  4.48it/s] 
Extracting : zlib-1.2.11-h7b6447c_3.conda:  66%|██████▌   | 23/35 [00:00<00:02,  4.48it/s]
Extracting : pysocks-1.7.1-py37_0.conda:  69%|██████▊   | 24/35 [00:00<00:02,  4.48it/s]  
Extracting : conda-package-handling-1.6.1-py37h7b6447c_0.conda:  71%|███████▏  | 25/35 [00:00<00:02,  4.48it/s]
Extracting : readline-8.0-h7b6447c_0.conda:  74%|███████▍  | 26/35 [00:00<00:02,  4.48it/s]                    
Extracting : cffi-1.14.0-py37he30daa8_1.conda:  77%|███████▋  | 27/35 [00:00<00:01,  4.48it/s]
Extracting : xz-5.2.5-h7b6447c_0.conda:  80%|████████  | 28/35 [00:00<00:01,  4.48it/s]       
Extracting : ld_impl_linux-64-2.33.1-h53a641e_7.conda:  83%|████████▎ | 29/35 [00:00<00:01,  4.48it/s]
Extracting : urllib3-1.25.8-py37_0.conda:  86%|████████▌ | 30/35 [00:00<00:01,  4.48it/s]             
Extracting : libstdcxx-ng-9.1.0-hdf63c60_0.conda:  89%|████████▊ | 31/35 [00:00<00:00,  4.48it/s]
Extracting : libgcc-ng-9.1.0-hdf63c60_0.conda:  91%|█████████▏| 32/35 [00:00<00:00,  4.48it/s]   
Extracting : libffi-3.3-he6710b0_1.conda:  94%|█████████▍| 33/35 [00:00<00:00,  4.48it/s]     
Extracting : conda-4.8.3-py37_0.tar.bz2:  97%|█████████▋| 34/35 [00:00<00:00,  4.48it/s] [0m[91m
                                                                                        [0m[91m
[0m
```

**Comment by champoll** [comment] 2020-10-22 21:04
I have seen the same issue. Usually reloading the autograder to Gradescope again fixes it.

**Comment by chrispyles** [comment] 2020-10-23 03:48
Yes, this is a known issue. We're not sure what the cause is as-yet but we'll keep this thread open with updates as we learn more.

**Comment by chrispyles** [comment] 2021-01-01 07:41
No updates. Seems to be an issue on Gradescope's end. Closing this thread but please reopen if there are new developments.

**Closed by chrispyles** 2021-01-01 07:41 UTC
Labels: bug
